version: '3'

services:
  minio:
    container_name: baltika_minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volumes/minio/:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data

  postgres:
    container_name: baltika_pg
    image: postgres:14.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./database_sql/db_table_creation.sql:/docker-entrypoint-initdb.d/db_table_creation.sql
      - ./database_sql/db_function_creation.sql:/docker-entrypoint-initdb.d/db_function_creation.sql
      - ./database_sql/db_data_insert.sql:/docker-entrypoint-initdb.d/db_data_insert.sql
    ports:
      - "5432:5432"
